/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ServiciosIndexLazyImport = createFileRoute('/servicios/')()
const NosotrosIndexLazyImport = createFileRoute('/nosotros/')()
const ContactoIndexLazyImport = createFileRoute('/contacto/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServiciosIndexLazyRoute = ServiciosIndexLazyImport.update({
  path: '/servicios/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/servicios/index.lazy').then((d) => d.Route),
)

const NosotrosIndexLazyRoute = NosotrosIndexLazyImport.update({
  path: '/nosotros/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/nosotros/index.lazy').then((d) => d.Route),
)

const ContactoIndexLazyRoute = ContactoIndexLazyImport.update({
  path: '/contacto/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contacto/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/contacto/': {
      preLoaderRoute: typeof ContactoIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/nosotros/': {
      preLoaderRoute: typeof NosotrosIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/servicios/': {
      preLoaderRoute: typeof ServiciosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ContactoIndexLazyRoute,
  NosotrosIndexLazyRoute,
  ServiciosIndexLazyRoute,
])

/* prettier-ignore-end */
